### ISSUE TITLE
gzip OSError

### ISSUE THREAD

**Issue by Moeflon** [pbloem/kgbench#1]
Loading any dataset (e.g. `data = kg.load('dblp')`) yields `OSError: Not a gzipped file (b've')` on Google Colab running Python 3.7.12.

kgbench was installed as follows:
```
git clone https://github.com/pbloem/kgbench kgbench_git
pip install pybind11
pip install -e kgbench_git/
```

**Comment by Moeflon** [comment]
Cloning using LFS did the trick! Maybe it could be helpful to add this to the README, as Colab does not have LFS installed by default?

`sudo apt-get install git-lfs`
`git lfs clone https://github.com/pbloem/kgbench`

**Comment by pbloem** [comment]
Thanks for the pointer! I've added some notes to the README.
